(() => {
  "use strict";
  const KEYS = { accounting: "breakfast-accounting-v1", payroll: "breakfast-payroll-v1", analysis: "breakfast-analysis-settings-v1" };
  const metaKey = name => "breakfast-" + name + "-cloud-meta-v1";
  const read = key => {
    const raw = localStorage.getItem(key);
    return raw ? JSON.parse(raw) : null;
  };
  const histories = () => [
    window.BREAKFAST_ACCOUNTING_HISTORY_2022_2025, window.BREAKFAST_ACCOUNTING_HISTORY_2026,
    window.BREAKFAST_ACCOUNTING_BACKUP_2026_07_22, window.BREAKFAST_UBER_STATEMENT_2026_07_24
  ].filter(Boolean).flatMap(item => item.transactions || []);
  function collect() {
    const saved = read(KEYS.accounting);
    const accounting = saved ? {
      ...saved,
      transactions: window.BreakfastAccountingStorage.hydrateTransactions(saved.transactions, histories(), { deletedIds: saved.historyDeletedIds }),
      storageMode: "full-history-v1"
    } : { version: 7, transactions: histories(), dayLabor: [], storageMode: "full-history-v1" };
    return {
      format: "breakfast-operations-backup", schemaVersion: 1, exportedAt: new Date().toISOString(),
      modules: { accounting, payroll: read(KEYS.payroll), analysis: read(KEYS.analysis) },
      moduleUpdatedAt: Object.fromEntries(["accounting", "payroll"].map(name => {
        const meta = read(metaKey(name)) || {};
        return [name, meta.lastLocalChangeAt || meta.lastSuccessAt || ""];
      })),
      historicalPayroll: Object.assign({}, window.BREAKFAST_SALARY_HISTORY_2022_2025?.payroll, window.BREAKFAST_SALARY_HISTORY_2026_H1?.payroll)
    };
  }
  function validate(value) {
    if (value?.format !== "breakfast-operations-backup" || value.schemaVersion !== 1 || !value.modules) throw new Error("請選擇整合營運備份 JSON 檔。");
    const { accounting, payroll, analysis } = value.modules;
    if (!accounting || !Number.isFinite(Number(accounting.version)) || !Array.isArray(accounting.transactions) || !Array.isArray(accounting.dayLabor)) throw new Error("備份中的記帳資料不完整。");
    if (payroll !== null && (!payroll || !Array.isArray(payroll.employees) || !payroll.settings || Array.isArray(payroll.settings))) throw new Error("備份中的薪資資料不完整。");
    if (analysis !== null && (!analysis || typeof analysis !== "object" || Array.isArray(analysis))) throw new Error("備份中的報表設定不完整。");
    return value;
  }
  function download(value, prefix = "初一食午_整合營運備份") {
    const url = URL.createObjectURL(new Blob([JSON.stringify(value)], { type: "application/json" }));
    const link = document.createElement("a");
    link.href = url;
    link.download = prefix + "_" + new Date().toLocaleDateString("sv-SE") + "_" + Date.now() + ".json";
    link.click();
    window.setTimeout(() => URL.revokeObjectURL(url), 60000);
  }
  async function apply(modules, options = {}) {
    const names = Object.keys(modules).filter(name => KEYS[name] && modules[name] !== null);
    const keys = [...names.map(name => KEYS[name]), ...names.filter(name => name !== "analysis").map(metaKey),
      "breakfast-payroll-summary-v1", "breakfast-accounting-summary-v1"];
    const previous = new Map(keys.map(key => [key, localStorage.getItem(key)]));
    await window.BreakfastOperationsStore.createSnapshot("operations", collect(), { label: options.label || "整合資料還原前快照" });
    if (keys.some(key => localStorage.getItem(key) !== previous.get(key))) throw new Error("另一個頁面剛更新資料，請重新核對後再試。");
    try {
      for (const name of names) {
        if (name === "accounting") window.BreakfastAccountingStorage.persist(KEYS[name], modules[name], histories());
        else localStorage.setItem(KEYS[name], JSON.stringify(modules[name]));
        if (name !== "analysis") {
          const meta = read(metaKey(name)) || {};
          const remote = options.remotes?.[name];
          localStorage.setItem(metaKey(name), JSON.stringify(remote
            ? { ...meta, dirty: false, revision: remote.revision, lastSuccessAt: remote.updatedAt, lastLocalChangeAt: remote.updatedAt }
            : { ...meta, dirty: true, lastLocalChangeAt: new Date().toISOString() }));
        }
      }
      // Summary caches are regenerated by the apps from the restored source data.
      localStorage.removeItem("breakfast-payroll-summary-v1");
      localStorage.removeItem("breakfast-accounting-summary-v1");
    } catch (error) {
      for (const [key, raw] of previous) {
        if (raw === null) localStorage.removeItem(key);
        else localStorage.setItem(key, raw);
      }
      throw error;
    }
    window.dispatchEvent(new CustomEvent("breakfast-operations-restored"));
  }
  window.BreakfastOperationsBackup = { KEYS, metaKey, read, collect, validate, download, apply };
})();
